# Generated by Django 5.2.3 on 2025-07-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmapitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='roadmapitem',
            name='priority',
        ),
    ]
